# Generated by Django 4.2.7 on 2025-04-18 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdImpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placement_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="广告位ID"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="用户代理"),
                ),
                ("channel", models.CharField(max_length=50, verbose_name="渠道")),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="地区"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="设备类型"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impressions",
                        to="ads.ad",
                        verbose_name="广告",
                    ),
                ),
            ],
            options={
                "verbose_name": "广告展示",
                "verbose_name_plural": "广告展示",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ad", "created_at"], name="delivery_ad_ad_id_4f41ff_idx"
                    ),
                    models.Index(
                        fields=["placement_id", "created_at"],
                        name="delivery_ad_placeme_d2164d_idx",
                    ),
                    models.Index(
                        fields=["channel", "created_at"],
                        name="delivery_ad_channel_c1d77e_idx",
                    ),
                    models.Index(
                        fields=["region", "created_at"],
                        name="delivery_ad_region_03331d_idx",
                    ),
                    models.Index(
                        fields=["device_type", "created_at"],
                        name="delivery_ad_device__10833c_idx",
                    ),
                ],
            },
        ),
    ]
