# Generated by Django 4.2.7 on 2025-04-18 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("delivery", "0001_initial"),
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="用户代理"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="ads.ad",
                        verbose_name="广告",
                    ),
                ),
                (
                    "impression",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="delivery.adimpression",
                        verbose_name="展示记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "广告点击",
                "verbose_name_plural": "广告点击",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ad", "created_at"], name="reporting_a_ad_id_e6cb66_idx"
                    ),
                    models.Index(
                        fields=["impression", "created_at"],
                        name="reporting_a_impress_dd4602_idx",
                    ),
                ],
            },
        ),
    ]
