# Generated by Django 4.2.7 on 2025-04-18 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_alter_ad_creative_image_adreviewlog"),
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdDailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="统计日期")),
                (
                    "impressions",
                    models.PositiveIntegerField(default=0, verbose_name="展示量"),
                ),
                (
                    "clicks",
                    models.PositiveIntegerField(default=0, verbose_name="点击量"),
                ),
                (
                    "spend",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="消耗金额",
                    ),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="ads.ad",
                        verbose_name="广告",
                    ),
                ),
            ],
            options={
                "verbose_name": "广告每日统计",
                "verbose_name_plural": "广告每日统计",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["ad", "date"], name="reporting_a_ad_id_692dd9_idx"
                    )
                ],
                "unique_together": {("ad", "date")},
            },
        ),
    ]
