# Generated by Django 4.2.7 on 2025-04-18 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_alter_ad_creative_image_adreviewlog"),
        ("reporting", "0002_addailystats"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdDeviceStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "桌面端"),
                            ("mobile", "移动端"),
                            ("tablet", "平板"),
                            ("other", "其他"),
                        ],
                        max_length=50,
                        verbose_name="设备类型",
                    ),
                ),
                ("date", models.DateField(verbose_name="统计日期")),
                (
                    "impressions",
                    models.PositiveIntegerField(default=0, verbose_name="展示量"),
                ),
                (
                    "clicks",
                    models.PositiveIntegerField(default=0, verbose_name="点击量"),
                ),
            ],
            options={
                "verbose_name": "广告设备统计",
                "verbose_name_plural": "广告设备统计",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AdRegionStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=100, verbose_name="地区")),
                ("date", models.DateField(verbose_name="统计日期")),
                (
                    "impressions",
                    models.PositiveIntegerField(default=0, verbose_name="展示量"),
                ),
                (
                    "clicks",
                    models.PositiveIntegerField(default=0, verbose_name="点击量"),
                ),
            ],
            options={
                "verbose_name": "广告地域统计",
                "verbose_name_plural": "广告地域统计",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="adclick",
            name="device_type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="设备类型"
            ),
        ),
        migrations.AddField(
            model_name="adclick",
            name="region",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="地区"
            ),
        ),
        migrations.AddIndex(
            model_name="adclick",
            index=models.Index(fields=["region"], name="reporting_a_region_dc647d_idx"),
        ),
        migrations.AddIndex(
            model_name="adclick",
            index=models.Index(
                fields=["device_type"], name="reporting_a_device__da1839_idx"
            ),
        ),
        migrations.AddField(
            model_name="adregionstats",
            name="ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="region_stats",
                to="ads.ad",
                verbose_name="广告",
            ),
        ),
        migrations.AddField(
            model_name="addevicestats",
            name="ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_stats",
                to="ads.ad",
                verbose_name="广告",
            ),
        ),
        migrations.AddIndex(
            model_name="adregionstats",
            index=models.Index(
                fields=["ad", "region", "date"], name="reporting_a_ad_id_6b0f48_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="adregionstats",
            unique_together={("ad", "region", "date")},
        ),
        migrations.AddIndex(
            model_name="addevicestats",
            index=models.Index(
                fields=["ad", "device_type", "date"],
                name="reporting_a_ad_id_e6f253_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="addevicestats",
            unique_together={("ad", "device_type", "date")},
        ),
    ]
