# Generated by Django 4.2.7 on 2025-04-18 02:17

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="广告标题")),
                ("target_url", models.URLField(verbose_name="目标链接")),
                (
                    "creative_image",
                    models.ImageField(
                        upload_to="ads/creatives/", verbose_name="广告素材"
                    ),
                ),
                (
                    "total_budget",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="总预算",
                    ),
                ),
                (
                    "daily_budget",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="每日预算",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                            ("running", "投放中"),
                            ("paused", "已暂停"),
                            ("finished", "已结束"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "reject_reason",
                    models.TextField(blank=True, null=True, verbose_name="拒绝原因"),
                ),
                (
                    "total_impressions",
                    models.PositiveIntegerField(default=0, verbose_name="总展示量"),
                ),
                (
                    "total_clicks",
                    models.PositiveIntegerField(default=0, verbose_name="总点击量"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "advertiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="广告主",
                    ),
                ),
            ],
            options={
                "verbose_name": "广告",
                "verbose_name_plural": "广告",
                "ordering": ["-created_at"],
            },
        ),
    ]
