# Generated by Django 4.2.7 on 2025-04-18 02:56

import ads.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="creative_image",
            field=models.ImageField(
                upload_to=ads.utils.get_upload_path,
                validators=[ads.utils.validate_image],
                verbose_name="广告素材",
            ),
        ),
        migrations.CreateModel(
            name="AdReviewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submit", "提交审核"),
                            ("approve", "通过"),
                            ("reject", "拒绝"),
                        ],
                        max_length=20,
                        verbose_name="审核动作",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="审核意见"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_logs",
                        to="ads.ad",
                        verbose_name="广告",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_ads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
            ],
            options={
                "verbose_name": "广告审核记录",
                "verbose_name_plural": "广告审核记录",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ad", "created_at"], name="ads_adrevie_ad_id_af780d_idx"
                    ),
                    models.Index(
                        fields=["reviewer", "created_at"],
                        name="ads_adrevie_reviewe_dda8cf_idx",
                    ),
                ],
            },
        ),
    ]
